on:
    workflow_dispatch:
    push:
      branches:
        - main
    pull_request:
  
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  runtests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.22'
          cache: true
  
      - name: Run tests
        run: |
            go version
            go test ./input