on: [push, pull_request_target, workflow_dispatch]
  
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  runtests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: github.event_name == 'push'
        uses: actions/checkout@v4
      - name: Checkout (PR)
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v4
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.22'
          cache: true
  
      - name: Run tests
        run: |
            go version
            go test ./input/rkg_input
            go test ./input/mii_input
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: github.event_name == 'push'
        uses: actions/checkout@v4
      - name: Checkout (PR)
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v4
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.22'
          cache: true
  
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60